### ISSUE TITLE
Exposed credentials

### ISSUE THREAD

**Issue by kecaneven** [MahmudulMannan08/FrameworkUIAutomation#1]
Hey @MahmudulMannan08

There are exposed credentials at:
 - https://github.com/MahmudulMannan08/FrameworkUIAutomation/blob/50c0cb118ae53f3e5088bb5dc1e04521c7cef7a6/FrameworkUIAutomation/UIHelper.cs#L218 

You may consider recycling credentials and moving sensitive data to environment variables to prevent from being committed to GitHub.

Please refer to the article for more info about Removing sensitive data from a repository: https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

Kind regards,
Neven

**Comment by MahmudulMannan08** [comment]
Hi @kecaneven ,
Thanks a lot for pointing that out. I maintain a separate file to credentials and use them as environment variables. I remove my credentials before committing to Github. Somehow this old repository got missed. I have removed that now. Thank you.
